alter table public.bride_profiles
    add column if not exists full_name text,
    add column if not exists wedding_date date,
    add column if not exists wedding_location text,
    add column if not exists country text,
    add column if not exists state text,
    add column if not exists notes text,
    add column if not exists profile_photo_url text,
    add column if not exists skin_type text,
    add column if not exists hair_type text,
    add column if not exists hair_density text,
    add column if not exists face_shape text,
    add column if not exists eye_color text,
    add column if not exists eye_shape text,
    add column if not exists hair_color text,
    add column if not exists hair_length text,
    add column if not exists inspo_urls text[],
    add column if not exists mood_items text[],
    add column if not exists updated_at timestamptz default now();
