alter table public.artist_profiles
    add column if not exists bio text,
    add column if not exists aesthetic text,
    add column if not exists specialties text[],
    add column if not exists best_for text[],
    add column if not exists not_ideal_for text[],
    add column if not exists starting_price text,
    add column if not exists travels boolean,
    add column if not exists website text,
    add column if not exists instagram text,
    add column if not exists profile_photo_url text,
    add column if not exists is_published boolean default true,
    add column if not exists tier text,
    add column if not exists portfolio_photos jsonb default '[]'::jsonb,
    add column if not exists profile_views integer default 0,
    add column if not exists inquiry_clicks integer default 0,
    add column if not exists is_active boolean default true,
    add column if not exists country text,
    add column if not exists email text,
    add column if not exists owner_name text,
    add column if not exists city text,
    add column if not exists state text,
    add column if not exists services text,
    add column if not exists business_name text;

do $$
declare
    seed record;
begin
    for seed in select * from (values
        ('Bailee Cribb Bridal', 'Bailee Cribb', 'Myrtle Beach', 'SC', 'Hair + Makeup', 'Specializing in Hollywood waves, structured bridal styling, and airbrushed makeup designed to hold in coastal heat, humidity, and long timelines. Signature: The Bailee Wave + Sculpt™.', 'Coastal editorial glam — structured, polished, engineered to hold.', array['Hollywood Waves','The Bailee Wave + Sculpt™','Airbrush','Structured Bridal Styling']::text[], array['Fine hair brides','Coastal/humid weddings','Longevity-focused brides','Editorial photography']::text[], array['Undone boho texture','Ultra-natural no-makeup','Loose unlstructured waves']::text[], 'Request quote', true, 'baileecribbbridal.com', nullif('', ''), nullif('', ''), true, 'signature', '[]'::jsonb, 0, 0, true, 'United States', 'bailee@baileecribbbridal.com'),
        ('Glamour Cosmetics', 'Sarah Levin', 'Boston', 'MA', 'Hair + Makeup', 'Named Best of Boston. Signature soft glam. A team that makes brides feel like the best version of themselves.', 'Modern soft glam — glowy, current, timeless.', array['Soft Glam','Bridal Waves','Airbrush','Inclusive skin-matching']::text[], array['All skin tones','Large parties','Soft and glowing looks']::text[], array['Heavy editorial','Extreme updos','Very dark/moody makeup']::text[], 'Request quote', true, 'glamourcosmetics.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'bookings@glamourcosmetics.com'),
        ('Samara Beauty', 'Nicole Samara Iyer', 'Santa Barbara', 'CA', 'Hair + Makeup', '15 years, 1,000+ weddings. Fresh elevated looks that last. Available for destination bookings.', 'Fresh, elevated, editorial bridal.', array['Hollywood Waves','Fresh elevated looks','All hair types','Longevity-focused']::text[], array['Destination weddings','Fine hair','Long timelines']::text[], array['Extreme editorial','Very heavy glam']::text[], 'Request quote', true, 'samarabeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'nicole@samarabeauty.com'),
        ('Triplow Beauty', 'Stacey Triplow', 'San Diego', 'CA', 'Hair + Makeup', '17+ years. Internationally acclaimed. Signature: luxe minimalism.', 'Luxe minimalism — enhancing, never overpowering.', array['Luxe minimalism','Editorial','Soft Glam']::text[], array['Editorial photography','Minimalist brides','Destination']::text[], array['Boho looks','Heavy full glam','Vintage-specific technique']::text[], 'Request quote', true, 'triplowbeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'book@triplowbeauty.com'),
        ('Etoilly Artistry', 'Maria Espinoza', 'Houston', 'TX', 'Hair + Makeup', 'Houston and Dallas studios. Built for large parties. Visionary team.', 'Luxury full-glam bridal — executed at scale.', array['Full Glam','Sculpted Updo','Airbrush','Large party logistics']::text[], array['Large bridal parties','Full glam brides','Humid climate']::text[], array['Minimal looks','Boho texture','Avant-garde']::text[], 'Request quote', true, 'etoillyartistry.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'hello@etoillyartistry.com'),
        ('Beauty Asylum', 'Jessica Cole', 'Charlotte', 'NC', 'Hair + Makeup', '16+ years. SE specialist. 5-star consistency across large parties.', 'Soft glam and chic — modern, effortless, Southeast-ready.', array['Soft Glam','Chic Bridal Styling','Airbrush','On-location SE']::text[], array['Southeast weddings','Soft glam brides','Scheduling-sensitive parties']::text[], array['Avant-garde','Very dark moody','Highly technical vintage']::text[], 'Request quote', true, 'beautyasylum.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'book@beautyasylum.com'),
        ('Torie Conn Artistry', 'Torie Conn', 'Chicago', 'IL', 'Makeup Only', 'ABC-TV, NYFW, celebrity clientele. Strong bold makeup specialist.', 'Bold editorial bridal — television technique on your wedding day.', array['Editorial','Full Glam','Bold Color','TV/Film technique']::text[], array['Bold brides','Editorial photography','TV-quality makeup']::text[], array['Hair styling','Soft understated looks']::text[], 'Request quote', false, 'torieconnartistry.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'torie@torieconnartistry.com'),
        ('Pre-Dame Beauty', 'Team', 'New York', 'NY', 'Hair + Makeup', 'NYC boutique team. Editorial eye applied to bridal.', 'NYC boutique editorial — elevated, feature-forward.', array['Editorial','Bold Glam','Sculpted Updo','Feature-based artistry']::text[], array['Editorial photography','Bold and graphic brides','NYC area']::text[], array['Natural boho looks','Minimal makeup','Standard traditional']::text[], 'Request quote', true, 'predamebeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'inquire@predamebeauty.com'),
        ('Wildeflower Collective', 'Analisa Marie', 'Portland', 'OR', 'Hair + Makeup', '13 years of inclusive bridal beauty. Every bride celebrated.', 'Luminous, skin-focused, inclusive.', array['Natural texture','Boho Waves','Minimal makeup','Inclusive beauty']::text[], array['Natural texture','Boho brides','Inclusive/LGBTQ+ weddings']::text[], array['Heavy full glam','Structured Hollywood waves','Dramatic updos']::text[], 'Request quote', true, 'wildeflowercollective.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'hello@wildeflowercollective.com'),
        ('J Fink Beauty', 'J Fink', 'Philadelphia', 'PA', 'Hair + Makeup', 'Connection between artist and bride is paramount. Luxury experience start to finish.', 'Polished, relationship-driven — you look like you, perfected.', array['Soft Glam','Classic Bridal','Natural-looking polish']::text[], array['Classic brides','Relationship-focused experience','PA/NJ area']::text[], array['Bold editorial','Heavy dark glam']::text[], 'Request quote', true, 'jfinkbeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'jfink@jfinkbeauty.com'),
        ('Beautiful Brides Philly', 'Dana Persia', 'Philadelphia', 'PA', 'Hair + Makeup', 'Dana Persia — 20 years, licensed esthetician. 1,500+ brides.', 'Refined classic bridal — polished, full-service.', array['Classic','Full Glam','Airbrush','Licensed esthetics']::text[], array['Classic and glam brides','Mature skin','Large parties']::text[], array['Boho texture','Editorial avant-garde']::text[], 'Request quote', false, 'beautifulbridesphilly.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'dana@beautifulbridesphilly.com'),
        ('Daniela Gozlan Bridal', 'Daniela Gozlan', 'Miami', 'FL', 'Makeup Only', 'Celebrity clients: Elle MacPherson, Paris Hilton. Bone structure and light are the technique.', 'Celebrity-level skin artistry — structure-based, luminous.', array['Celebrity technique','Editorial','Natural glow','Bone-structure artistry']::text[], array['Celebrity-level finish','Editorial photography','Destination Miami']::text[], array['Hair styling','Standard traditional']::text[], 'Request quote', true, 'danielagozlanbridal.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'daniela@danielagozlanbridal.com'),
        ('I.M. Artistry', 'Team', 'Tacoma', 'WA', 'Hair + Makeup', 'Atelier-trained luxury team. Tacoma and Kirkland. Every bride treated like royalty.', 'Opulent, luxury bridal — atelier-trained.', array['Luxury updo','Classic waves','Formal bridal','Full Glam']::text[], array['Formal venues','Updo brides','Luxury experience']::text[], array['Boho or undone looks','Ultra-minimal makeup']::text[], 'Request quote', true, 'imartistry.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'book@imartistry.com'),
        ('Teresa Miranda Beauty', 'Teresa Miranda', 'Los Angeles', 'CA', 'Hair + Makeup', 'Full-service skin prep + wedding day artistry. Studio for pre-wedding facials, lash lifts, brow.', 'Skin-first bridal — prep, glow, polish from the ground up.', array['Skin prep + day-of','Dewy glow','Soft Glam','Lash/brow work']::text[], array['Skin-conscious brides','Dewy/glowing looks','LA area']::text[], array['Heavy full glam','Dramatic updo','Bold editorial']::text[], 'Request quote', true, 'tmirandabeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'teresa@tmirandabeauty.com'),
        ('Emily Lynn & Co.', 'Emily Lynn', 'Los Angeles', 'CA', 'Hair + Makeup', 'Published nationwide, film and TV. Good vibes and great beauty for the cool-girl bride.', 'Cool-girl bridal — published, editorial, effortless.', array['Cool-girl editorial','Boho waves','Natural texture','Published editorial']::text[], array['Boho brides','Editorial photography','Cool/casual vibe']::text[], array['Traditional classic','Heavy glam','Formal structured updos']::text[], 'Request quote', true, 'emilylynnandc.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'book@emilylynnandc.com'),
        ('Mansi Bridal', 'Mansi Patel', 'Edison', 'NJ', 'Hair + Makeup', 'South Asian specialist. 7 years. Highlights natural beauty across all skin tones.', 'South Asian and multicultural bridal — rich, precise, celebratory.', array['South Asian bridal','Diverse skin tones','Traditional + modern fusion']::text[], array['South Asian weddings','Diverse skin tones','NJ/NY area']::text[], array['Very minimal looks','Boho undone styling']::text[], 'Request quote', true, 'mansibridal.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'mansi@mansibridal.com'),
        ('Page Beauty', 'Tanya Bures', 'New York', 'NY', 'Hair + Makeup', 'Founded 2013. Every client is already their best version. Effortless, chic, timeless.', 'Refined effortless — every client already their best version.', array['Natural-looking beauty','Soft elegant','Effortless polish']::text[], array['Minimalist brides','Natural beauty','NYC area']::text[], array['Heavy drama','Full glam','Bold editorial']::text[], 'Request quote', true, 'pagebeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'tanya@pagebeauty.com'),
        ('Innovations by Jen', 'Jennifer', 'Cleveland', 'OH', 'Makeup Only', '35+ years. Traditional and airbrush. Ohio regional specialist.', 'Classic, confidence-building — 35 years of expertise.', array['Traditional + airbrush','Classic bridal','Mature skin']::text[], array['Classic brides','Mature skin','Ohio/Midwest']::text[], array['Hair styling','Bold editorial','Heavy dark makeup']::text[], 'Request quote', false, 'innovationsbyjenmakeup.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'jen@innovationsbyjenmakeup.com'),
        ('Kim Baker Beauty', 'Kim Baker', 'Nashville', 'TN', 'Hair + Makeup', 'Nashville bridal specialist. Strong soft glam and polished wave work.', 'Nashville-chic — polished, warm, photographically flawless.', array['Soft Glam','Bridal Waves','Editorial','Airbrush']::text[], array['Southern weddings','Airbrush finish','Editorial photography']::text[], array['Ultra-minimal','Boho undone','Heavy vintage']::text[], 'Request quote', true, 'kimbakerbeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'kim@kimbakeerbeauty.com'),
        ('Blush & Co.', 'Lauren Hughes', 'Atlanta', 'GA', 'Hair + Makeup', 'Atlanta-based team. Warm, polished bridal beauty for the Southern bride.', 'Southern refined — warm, classic, consistently beautiful.', array['Soft Glam','Classic Bridal','Airbrush','Large parties']::text[], array['Southern venues','Large parties','Classic glam']::text[], array['Extreme editorial','Very dark makeup','Boho texture']::text[], 'Request quote', true, 'blushandco.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'hello@blushandco.com'),
        ('Abbi Neel Makeup Artistry', 'Abbi Neel', 'Boston', 'MA', 'Makeup Only', '8+ years. Dedicated to personalized, unique experience for each bride.', 'Personalized, unique — each bride''s beauty expressed.', array['Personalized bridal','Soft Glam','Natural-looking']::text[], array['Boston area','Personalized experience','Natural-looking makeup']::text[], array['Hair styling','Very bold/editorial']::text[], 'Request quote', true, 'abbineelmakeup.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'abbi@abbineelmakeup.com'),
        ('Erica Cassell Beauty', 'Erica Cassell', 'Charleston', 'SC', 'Hair + Makeup', 'Charleston coastal bridal specialist. Soft and polished looks that hold in humidity.', 'Coastal charm — effortless, Southern, glowing.', array['Coastal Bridal','Soft Glam','Bridal Waves','Airbrush']::text[], array['Coastal weddings','Humidity resistance','Charleston/SC area']::text[], array['Very heavy glam','Extreme editorial']::text[], 'Request quote', true, 'ericacassellbeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'erica@ericacassellbeauty.com'),
        ('TEAM Inc.', 'Marlynda Romero', 'Tampa', 'FL', 'Hair + Makeup', '20+ years. Natural-looking timeless styles. LGBTQ+ allies. Grooms and groomsmen welcome.', 'Natural, timeless, inclusive — 20+ years of dream-job passion.', array['Natural wedding styles','Timeless elegant','Groom/groomsmen','LGBTQ+ inclusive']::text[], array['Natural brides','Inclusive weddings','Groom styling','FL heat']::text[], array['Heavy editorial','Extreme updos']::text[], 'Request quote', true, 'teaminc.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'team@teaminc.com'),
        ('Brittany Renee Beauty', 'Brittany Renee', 'Phoenix', 'AZ', 'Hair + Makeup', 'Phoenix bridal specialist. Expert in longevity in extreme heat. Airbrush specialist.', 'Desert glam — airbrush-ready, heat-proof, polished.', array['Desert Bridal','Airbrush','Full Glam','Longevity in heat']::text[], array['Desert/outdoor weddings','Extreme heat','Full glam in heat']::text[], array['Very natural/minimal looks','Boho undone texture']::text[], 'Request quote', true, 'brittanyreneebeauty.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'brittany@brittanyreneebeauty.com'),
        ('Luxe Artistry', 'Victoria Chen', 'San Francisco', 'CA', 'Hair + Makeup', 'SF-based editorial bridal artist. Specializes in Asian skin tones and editorial aesthetics.', 'Modern editorial — clean, precise, skin-forward.', array['Editorial','Minimalist','Asian skin tones','Soft Glam']::text[], array['Editorial photography','Asian skin tones','Minimalist brides']::text[], array['Heavy traditional glam','Very boho undone']::text[], 'Request quote', true, 'luxeartistry.com', nullif('', ''), nullif('', ''), true, 'directory', '[]'::jsonb, 0, 0, true, 'United States', 'victoria@luxeartistry.com')
    ) as v(business_name, owner_name, city, state, services, bio, aesthetic, specialties, best_for, not_ideal_for, starting_price, travels, website, instagram, profile_photo_url, is_published, tier, portfolio_photos, profile_views, inquiry_clicks, is_active, country, email)
    loop
        update public.artist_profiles
        set
            business_name = seed.business_name,
            owner_name = seed.owner_name,
            city = seed.city,
            state = seed.state,
            services = seed.services,
            bio = seed.bio,
            aesthetic = seed.aesthetic,
            specialties = seed.specialties,
            best_for = seed.best_for,
            not_ideal_for = seed.not_ideal_for,
            starting_price = seed.starting_price,
            travels = seed.travels,
            website = seed.website,
            instagram = coalesce(seed.instagram, instagram),
            profile_photo_url = coalesce(seed.profile_photo_url, profile_photo_url),
            is_published = seed.is_published,
            tier = seed.tier,
            portfolio_photos = seed.portfolio_photos,
            profile_views = coalesce(profile_views, seed.profile_views),
            inquiry_clicks = coalesce(inquiry_clicks, seed.inquiry_clicks),
            is_active = seed.is_active,
            country = seed.country,
            email = seed.email
        where lower(coalesce(email, '')) = lower(seed.email)
           or lower(coalesce(business_name, '')) = lower(seed.business_name);
    end loop;
end $$;
